(program) @form
(here_string) @form
(comment) @form
(box) @form
(number) @form
(string) @form
(list) @form
(block_comment) @form
(sexp_comment) @form
(symbol) @form
(string) @form
(keyword) @form
(extension) @form
(lang_name) @form
(graph) @form
(dot) @form
(decimal) @form
(hash) @form
(vector) @form
(quote) @form
(quasiquote) @form
(syntax) @form
(quasisyntax) @form
(unquote) @form
(unquote_splicing) @form
(unsyntax) @form
(unsyntax_splicing) @form
