name: Tests

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: 
        - v0.10.4
        - nightly
    steps:
    - uses: actions/checkout@v2

    - uses: extractions/setup-just@v1

    - name: Run tests [${{ matrix.channel }}]
      run: just test ${{ matrix.channel }}
